In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

In [2]:
webpage=requests.get('https://www.makaan.com/price-trends').text

In [3]:
soup=BeautifulSoup(webpage,'lxml')

In [26]:
formats_all = []
formats_on_page = soup.select("td.ta-l a.link-block")
for product_format in formats_on_page:
    formats_all.append(product_format.get_text())

In [33]:
# formats_all

In [32]:
# formats_all.unique()

# pd.unique(formats_all)

In [38]:
formats_all = []
formats_on_page = soup.select("td.ta-r")
for product_format in formats_on_page:
    formats_all.append(product_format.get_text())

In [57]:
# formats_all

In [42]:
company=soup.find_all('tr',itemtype_='http://schema.org/Place')

In [44]:
inputTag = soup.findAll(attrs={"tr" : "http://schema.org/Place"})

In [45]:
inputTag

[]

In [64]:
len(soup.findAll("span", itemprop="name"))

2216

In [60]:
formats_all = []
formats_on_page = soup.select("td.growth")
for product_format in formats_on_page:
    formats_all.append(product_format.get_text())

In [62]:
len(formats_all)

1772

In [88]:
rating =[]
for i in com:
    rating.append(i.find('a',class_='link-block').text.strip())

AttributeError: 'NoneType' object has no attribute 'get_text'

In [99]:
soup.find_all('td',class_='ta-r')

<td class="ta-r" itemscope="" itemtype="http://schema.org/UnitPriceSpecification"><span class="currency"></span> <span itemprop="minPrice">611</span> - <span itemprop="maxPrice">1,71,969 / sqft</span></td>

In [77]:
com = soup.findAll("tr", itemscope="")
len(com)

2226

In [100]:
# formats_all = []
# formats_on_page = com.select("a.link-block")
# for product_format in formats_on_page:
#     formats_all.append(product_format.get_text())

In [101]:
# com

In [ ]:
name=[]
rating=[]
reviews=[]
ctype=[]
hq=[]
how_old=[]
no_of_employee=[]

for i in com:

  name.append(i.find('h2').text.strip())
  rating.append(i.find('p',class_='rating').text.strip())
  reviews.append(i.find('a' , class_='review-count').text.strip())
  ctype.append(i.find_all('p',class_='infoEntity')[0].text.strip())
  hq.append(i.find_all('p',class_='infoEntity')[1].text.strip())
  how_old.append(i.find_all('p',class_='infoEntity')[2].text.strip())
  no_of_employee.append(i.find_all('p',class_='infoEntity')[3].text.strip())

In [102]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 136:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=25&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
       'Description':desc,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136

<ipython-input-102-3a06ae9b3182>:118: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [103]:
final.to_excel("Nagpur_Dataset.xlsx")

In [104]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 25:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=26&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
       'Description':desc,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25

<ipython-input-104-70808001612f>:118: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [105]:
final.to_excel("Coimbatore_Dataset.xlsx")

In [106]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 156:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=28&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
       'Description':desc,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156

<ipython-input-106-6798b34fd2b7>:118: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [107]:
final.to_excel("Jaipur_Dataset.xlsx")

In [108]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 14:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=30&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
       'Description':desc,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

2
3
4
5
6
7
8
9
10
11
12
13
14

<ipython-input-108-daf94132c436>:118: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [109]:
final.to_excel("Kochi_Dataset.xlsx")

In [116]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 69:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=31&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
       'Description':desc,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69

<ipython-input-116-4ab9b27c5791>:118: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [117]:
final.to_excel("Bhubaneswar_Dataset.xlsx")

In [113]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 26:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=35&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
       'Description':desc,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26

<ipython-input-113-228dd762e16a>:118: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [114]:
final.to_excel("nashik_Dataset.xlsx")

In [118]:
final

,Type_of_plot,City,Total Price,Unit,Rupee_per_area,Type,Open_Date,Description,Area,Apartement
0,3 BHK Apartment,Bhubaneswar,61.33 L,L,"3,648 / sq ft",Under Construction,Possession by Jan 2024,3 BHK in Jatani Bhubaneswar:Well designed 3 b...,1681,3 BHK Apartment
1,4 BHK Apartment,Bhubaneswar,65.95 L,L,"3,637 / sq ft",Under Construction,Possession by Jan 2024,4 BHK in Jatani Bhubaneswar:Itâs a 4 bhk mu...,1813,4 BHK Apartment
2,3 BHK Apartment,Bhubaneswar,68.4 L,L,"3,632 / sq ft",Under Construction,Possession by Jan 2024,3 BHK in Jatani Bhubaneswar:Itâs a 3 bhk mu...,1883,3 BHK Apartment
3,3 BHK Apartment,Bhubaneswar,1.15 Cr,Cr,"6,216 / sq ft",Ready to move,3 Bathrooms,3 BHK in Rasulgarh Bhubaneswar:A 3 bhk proper...,1850,3 BHK Apartment
4,2 BHK Apartment,Bhubaneswar,48 L,L,"4,833 / sq ft",Ready to move,2 Bathrooms,2 BHK in Rudrapur Bhubaneswar:This spacious 2...,993,2 BHK Apartment
...,...,...,...,...,...,...,...,...,...,...
1355,1 BHK Apartment,Bhubaneswar,75 L,L,"9,894 / sq ft",Ready to move,1 Bathrooms,1 BHK in Chandrasekharpur Bhubaneswar:Well de...,758,1 BHK Apartment
1356,3 BHK Apartment,Bhubaneswar,69 L,L,"4,600 / sq ft",Under Construction,3 Bathrooms,3 BHK in Dumduma Bhubaneswar:This spacious 3 ...,1500,3 BHK Apartment
1357,2 BHK Apartment,Bhubaneswar,56.6 L,L,"6,373 / sq ft",Under Construction,2 Bathrooms,2 BHK in Patrapada Bhubaneswar:2 BHK Apartmen...,888,2 BHK Apartment
1358,3 BHK Apartment,Bhubaneswar,49.5 L,L,"3,928 / sq ft",Under Construction,2 Bathrooms,3 BHK in Balianta Bhubaneswar:A spacious 3 bh...,1260,3 BHK Apartment
1359,2 BHK Apartment,Bhubaneswar,46.78 L,L,"4,363 / sq ft",Under Construction,2 Bathrooms,2 BHK in Kalarahanga Bhubaneswar:A 2 bhk prop...,1072,2 BHK Apartment

In [119]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 108:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=23&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
       'Description':desc,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108

<ipython-input-119-851756a0f04c>:118: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [120]:
final.to_excel("Lucknow_Dataset.xlsx")

In [121]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 81:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=24&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
       'Description':desc,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81

<ipython-input-121-9754715bb558>:118: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [122]:
final.to_excel("Chandigarh_Dataset.xlsx")

In [123]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 147:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=41&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
       'Description':desc,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147

<ipython-input-123-b779b7106bbd>:118: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [124]:
final.to_excel("Visakhapatnam_Dataset.xlsx")

In [125]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 140:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=40&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
       'Description':desc,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140

<ipython-input-125-8ae44bdafbb9>:118: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [126]:
final.to_excel("Surat_Dataset.xlsx")

In [129]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 107:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=51&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107

In [141]:
df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

<ipython-input-141-80ce18d899a1>:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [140]:
print(len(plot))
print(len(city))
print(len(money))
print(len(unit))
print(len(rup_per_area))
print(len(type))
print(len(side_open))
print(len(desc))
print(len(unitarea))
print(len(apartement))

260
260
260
260
260
260
260
234
260
260

In [133]:
final.to_excel("Kanpur_Dataset.xlsx")

In [134]:
final

,Type_of_plot,City,Total Price,Unit,Rupee_per_area,Type,Open_Date,Area,Apartement
0,2 BHK Apartment,Kanpur,40 L,L,"5,000 / sq ft",Ready to move,3 years old,800,2 BHK Apartment
1,1 BHK Apartment,Kanpur,12 L,L,"3,428 / sq ft",Ready to move,1 Bathrooms,350,1 BHK Apartment
2,3 BHK Apartment,Kanpur,49 L,L,"3,266 / sq ft",Ready to move,122 - 123 years old,1500,3 BHK Apartment
3,3 BHK Apartment,Kanpur,45 L,L,"3,000 / sq ft",Ready to move,122 - 123 years old,1500,3 BHK Apartment
4,3 BHK Apartment,Kanpur,59 L,L,"3,933 / sq ft",Ready to move,5 years old,1500,3 BHK Apartment
...,...,...,...,...,...,...,...,...,...
2115,2 BHK Apartment,Kanpur,29 L,L,"2,761 / sq ft",Ready to move,122 - 123 years old,1050,2 BHK Apartment
2116,3 BHK Apartment,Kanpur,95 L,L,"6,333 / sq ft",Ready to move,6 years old,1500,3 BHK Apartment
2117,2 BHK Apartment,Kanpur,35 L,L,"3,333 / sq ft",Ready to move,122 - 123 years old,1050,2 BHK Apartment
2118,3 BHK Apartment,Kanpur,73 L,L,"5,407 / sq ft",Ready to move,7 - 8 years old,1350,3 BHK Apartment
2119,3 BHK Apartment,Kanpur,75 L,L,"5,000 / sq ft",Ready to move,122 - 123 years old,1500,3 BHK Apartment

In [137]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 66:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=38&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
       'Description':desc,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66

<ipython-input-137-484f6adcfe2e>:118: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [142]:
final.to_excel("Vadodara_Dataset.xlsx")

In [139]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 14:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=44&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

2
3
4
5
6
7
8
9
10
11
12
13
14

In [ ]:
final.to_excel("Patna_Dataset.xlsx")

In [144]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 10:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=57&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

2
3
4
5
6
7
8
9
10

In [145]:
print(len(plot))
print(len(city))
print(len(money))
print(len(unit))
print(len(rup_per_area))
print(len(type))
print(len(side_open))
print(len(desc))
print(len(unitarea))
print(len(apartement))

180
180
180
180
180
180
180
162
180
180

In [146]:

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

<ipython-input-146-80ce18d899a1>:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [147]:
final.to_excel("Haridwar_Dataset.xlsx")

In [148]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 25:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=63&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25

In [149]:
print(len(plot))
print(len(city))
print(len(money))
print(len(unit))
print(len(rup_per_area))
print(len(type))
print(len(side_open))
print(len(desc))
print(len(unitarea))
print(len(apartement))

480
480
480
480
480
480
480
456
480
480

In [150]:
    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

<ipython-input-150-80ce18d899a1>:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [151]:
final.to_excel("Guwahati_Dataset.xlsx")

In [152]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 13:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=78&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

2
3
4
5
6
7
8
9
10
11
12
13

In [153]:
print(len(plot))
print(len(city))
print(len(money))
print(len(unit))
print(len(rup_per_area))
print(len(type))
print(len(side_open))
print(len(desc))
print(len(unitarea))
print(len(apartement))

240
240
240
240
240
240
240
228
240
240

In [154]:
  

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

<ipython-input-154-80ce18d899a1>:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [155]:
final.to_excel("Mathura_Dataset.xlsx")

In [ ]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 90:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=88&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

In [ ]:
final.to_excel("Faridabad_Dataset.xlsx")

In [ ]:
final=pd.DataFrame()
page = 1
plot = []
city= []
money = []
unit = []
rup_per_area = []
unitarea = []
type = []
side_open = []
desc=[]
apartement = []
project_Name = []

while page != 103:
    
    webpage=requests.get("https://www.makaan.com/listings?cityId=166&listingType=buy&propertyType=apartment&page={page}").text
    soup=BeautifulSoup(webpage,'lxml')


    try:
        formats_on_page = soup.select("div.title-line a.typelink")
        for product_format in formats_on_page:
            plot.append(product_format.get_text())
    except:
        plot.append(np.nan)

    try:
        formats_on_page = soup.select("span.cityName")
        for product_format in formats_on_page:
            city.append(product_format.get_text())
    except:
        city.append(np.nan)
   
    try:
        formats_on_page = soup.select("td.price")
        for product_format in formats_on_page:
            money.append(product_format.get_text())
    except:
        money.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.val")
        for product_format in formats_on_page:
            type.append(product_format.get_text()) 
    except:
        type.append(np.nan)

    try:
        formats_on_page = soup.select("span.unit")
        for product_format in formats_on_page:
            unit.append(product_format.get_text()) 
    except:
        unit.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.rate")
        for product_format in formats_on_page:
            rup_per_area.append(product_format.get_text())
    except:
        rup_per_area.append(np.nan)
        
    try:
        formats_on_page = soup.select("tr.hcol td.size")
        for product_format in formats_on_page:
            unitarea.append(product_format.get_text())
    except:
        unitarea.append(np.nan)
    
    try:
        company=soup.find_all('ul',class_='listing-details')
        for i in company:
            side_open.append(i.find_all('li',class_='keypoint')[0].text.strip())
    except:
        side_open.append(np.nan)
    
    try:
        formats_on_page = soup.select("div.listing-description")
        for product_format in formats_on_page:
            desc.append(product_format.get_text())
    except:
        desc.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.typelink")
        for product_format in formats_on_page:
            apartement.append(product_format.get_text())
    except:
        apartement.append(np.nan)
    
    
    try:
        formats_on_page = soup.select("a.projName")
        for product_format in formats_on_page:
            project_Name.append(product_format.get_text())
    except:
        project_Name.append(np.nan)
    
    page = page + 1
    print(page)

    

df=pd.DataFrame({'Type_of_plot':plot,
       'City':city,
       'Total Price':money,
       'Unit':unit,
       'Rupee_per_area':rup_per_area,
       'Type':type,
       'Open_Date':side_open,
        'Area' :unitarea,
        "Apartement":apartement
})

  
final=final.append(df,ignore_index=True)

In [ ]:
final.to_excel("Raipur_Dataset.xlsx")